name: Continous Integration Workflow

on:
  pull_request:
    branches: 
      - "dev"
      - "testing"
      - "main"

permissions: write-all

jobs:
  testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./coffee_app/
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.15.0
        cache: 'npm'
        cache-dependency-path: './coffee_app/package-lock.json'
    - name: Install dependencies
      run: npm install 
    - name: Run unit tests
      run: npm run test:unit
    - name: Install Playwright
      run: npx playwright install
    - name: Run integration tests 
      run: npm run test

  formatting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./coffee_app/
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{github.head_ref}}
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.15.0
        cache: 'npm'
        cache-dependency-path: './coffee_app/package-lock.json'
    - name: Install dependencies
      run: npm install 
    - name: run Formatter
      run: npm run format
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        commit_message: Applied formatting changes
        branch: ${{github.head_ref}}

  linting:
    needs: formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./coffee_app/
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{github.head_ref}}
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.15.0
        cache: 'npm'
        cache-dependency-path: './coffee_app/package-lock.json'
    - name: Install dependencies
      run: npm install 
    - name: run Linter
      run: npm run lint
    
