name: Continous Integration Workflow

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.15.0
        cache: 'npm'
        cache-dependency-path: coffee_app/package-lock.json

    - name: Enter into coffee_app folder
      run: cd coffee_app

    - name: Install dependencies
      run: npm install 
    - name: Run unit tests
      run: npm run test:unit
    - name: Install Playwright
      run: npx playwright install
    - name: Run integration tests 
      run: npm run test
